### ISSUE TITLE
Change colour of "Read More" text

### ISSUE THREAD

**Issue by SlaviPana** [jedfoster/Readmore.js#154]
Hello,

I would like to change the colour and make it bold of the text that appears. Can you please help me out how to do it?

**Comment by jedfoster** [comment]
Use CSS. Something like:

```css
[data-readmore-toggle] {
  color: pink;
  font-weight: bold;
}
```

Put that in your site CSS or inside a `<style>` tag on your page.
