### ISSUE TITLE
collapsedHeight not being applied, unable to override default 200px height

### ISSUE THREAD

**Issue by ericakfranz** [jedfoster/Readmore.js#96]
Everything else is functioning as expected, but I'm unable to modify the default 200px height that is injected into the collapsed div. 

Currently using readmore at http://staging.thsrestaurant.com - login is 'preview' and pass is 'preview' to view the front-end. Scroll down to the first text section or select the "Our Story" menu link.

Originally I added the following to the attached global.js theme file but moved it directly to the footer to see if that was an issue - still no luck:
`$('#readmore').readmore({
  collapsedHeight: 260
});`

Even modifying the readmore.min.js file directly had no effect and the div continued to use height: 200px when collapsed. No caching enabled on the site, no error output. Happens with or without an image in the div.

Showing this same issue in Chrome, Firefox, Opera and Safari on Mac; haven't tested IE at this time.

**Comment by lbw8lrrh** [comment]
I noticed in your code that the div that contains the text you are trying to toggle is set to 200px. This would override whatever you set for the readmore js. See what happens if you remove this style. 

```
<div id="readmore" class="readmore-js-section readmore-js-collapsed" style="height: 200px;">
```
Also, either put your code at the bottom of your html file after the close body tag. If you want to change the default height across your site, you could also go directly into the js file and change the default collapsedHeight variable.

**Comment by ericakfranz** [comment]
That's the style being added by ReadMore, before being modified by ReadMore it's just a div with the ID used to target the section:

`<div id="readmore"></div>`

Changing the `collapsedHeight` variable makes no change. Site has no caching enabled, also tried with all other JS removed and no change.

Tried moving the position of the readmore.js file with no luck. 

Thanks for the feedback, looks like you haven't run across this issue previously? :)

**Comment by lbw8lrrh** [comment]
Looked at your code again—are you doing this in wordpress? When I've used this it has been on pure html/css/js site. Just to recreate what I did that works for me:

Call jquery in the head:
```javascript
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>	 
```
Put content inside:
```javascript
<div class="inner"></div>
```

At the bottom I call the script and set embedCSS to false so I can manipulate the height using CSS:
```javascript
<script src="js/jquery.readmore.js"></script>
<script>
	$('.inner').readmore({
		embedCSS: false,
  		speed: 200,
});  
</script>
```

I actually use readmore for a newsletter so I have several different articles, all of which have different max-heights, so I manipulate them in my css file:

```css
#featured .inner{
		max-height: 210px;
}

#newsflash .inner{
		max-height: 175px;
}

#productivity .inner{
		max-height: 170px;
}
```

I also styled the Read more/Read less links using css:
```css
.toggle {
	padding: 0 1em 0 0;
	font-size: .9em;
	line-height: 3em;
	display: block;
	text-align: right;
	font-family: "HelveticaNeueMedium", "HelveticaNeue-Medium", "Helvetica Neue 	
	Medium", "HelveticaNeue", "Helvetica Neue", "Roboto", 
	sans-serif; font-weight:500; font-stretch:normal; 		
}
```
Not sure if that helps. Might be something interacting with wordpress.
